##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## FINALLY
##

SRC	=	./test.hs

NAME	=	pushswap_checker

CFLAGS	=	-Wall -Wextra

all:		$(NAME)

$(NAME):
		ghc -o $(NAME) $(SRC)
clean:
		rm -f $(OBJ)

fclean:		clean
		rm -f $(NAME)

re:		fclean all
