#!/usr/bin/env python3
import sys
import time
import math

argc = len(sys.argv)
argv = sys.argv

def help():
    if argv[1] == "-h" and argc == 2:
        print("USAGE")
        print("\t./203hotline [n k | d]")
        print("")
        print("DESCRIPTION")
        print("\tn\tn value for the computation of C(n, k)")
        print("\td\tk value for the computation of C(n, k)")
        print("\tk\taverage duration of calls (in seconds)")
        exit(0)


def binomial_coefficient(n, k):
    if k > n - k:
        k = n - k
    res = 1
    for i in range(k):
        res *= (n - i)
        res //= (i + 1)
    return res


def binomial_distribution(n, p):
    q = 1 - p
    b = [0] * (n + 1)
    b[0] = pow(q, n)
    for i in range(1, n + 1):
        b[i] = (b[i - 1] * p * (n - i + 1)) / (q * i)
    return b


def poisson_distribution(n, lambd):
    p = [0] * (n + 1)
    p[0] = math.exp(-lambd)
    for i in range(1, n + 1):
        p[i] = (p[i - 1] * lambd) / i
    return p

def error():
    print("ERROR")
    exit(84)

def main():
    # Parse command-line arguments
    help()
    if argc != 2 or argc != 3:
        error()
    if argc == 3:
        n = int(argv[1])
        k = int(argv[2])
        if n < 0 or k < 0 or k > n:
            error()
        print('{}-combinations of a set of size {}:'.format(k, n))
        print(binomial_coefficient(n, k))
        return 0

    elif argc == 2:
        exit(0)


if __name__ == "__main__":
    main()