##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## FINALLY
##

re: clean
	cd generator && make re && cd ..
	cd solver && make re && cd ..

clean:
	cd generator && make clean && cd ..
	cd solver && make clean && cd ..

fclean:		clean
		cd generator && make fclean && cd ..
		cd solver && make fclean && cd ..