##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## FINALLY
##

re: clean
	cd antman && make re && cd ..
	cd giantman && make re && cd ..

clean:
	cd antman && make clean && cd ..
	cd giantman && make clean && cd ..